// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxdwjfvtrllrimytryxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZHdqZnZ0cmxscmlteXRyeXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjIwODIsImV4cCI6MjA2MjUzODA4Mn0.-6jZevnurhhpL5u_Crm4LcBTEdiOMirM-Xlo1Opg6lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);